spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost/bootdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    platform: mysql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
